spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: postgres
    password: spintechs
    initialization-mode: always
  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  application:
    name: todo-app
logging:
  level:
    ${spring.application.name}: debug
  file:
    path: './logs'
    name: ${logging.file.path}/todo.log
app:
  jwt:
    jwtExpiration: 86400000
    jwtSecret: bezKoderSecretKeybezKoderSecretKeybezKoderSecretKeybezKoderSecretKeybezKoderSecretKeybezKoderSecretKeybezKoderSecretKeybezKoderSecretKeybezKoderSecretKeybezKoderSecretKey
server:
  error:
    include-stacktrace: on_trace_param
  port: 8081
javers:
  newObjectSnapshot: true

