spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: postgres
    password: spintechs
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: todo-app
logging:
  level:
    ${spring.application.name}: debug
  file:
    path: './logs'
    name: ${logging.file.path}/todo.log
app:
  jwt:
    expiration-period: 14
    key: lskdkajshgdfiuaysdgfiuaysdgfiuasdgyfiuasdgyfiausdyf